services:
  portfolio:
    image: ${PORTFOLIO_IMAGE:-mm-saiful6854/portfolio-md-saiful-islam:latest}
    container_name: portfolio
    restart: unless-stopped
    pull_policy: always
    ports:
      - "${PORT:-80}:80"
